server:
  port: 8888
  db_url: "postgres://zhiruchen@localhost:5432/chat"
  base_dir: "/tmp/chat_server"
auth:
  private_key: |
    -----BEGIN PRIVATE KEY-----
    MC4CAQAwBQYDK2VwBCIEIFpLYd35hdfAJNhHSELQcE6kUzut58UQ/yVR6lndBKX0
    -----END PRIVATE KEY-----
  public_key: |
    -----BEGIN PUBLIC KEY-----
    MCowBQYDK2VwAyEAT0Sx8SxDZmkz2WNTOy4LqcY2eK11DUolrEnULI9EJFQ=
    -----END PUBLIC KEY-----