server:
  port: 8888
  db_url: "postgres://postgres:postgres_admin@localhost:5432/chat"
auth:
  private_key: |
    -----BEGIN PRIVATE KEY-----
    MC4CAQAwBQYDK2VwBCIEIFvFrAAH2xzDmS1tYh6582YimuB0DgazNpik1kVEsNFv
    -----END PRIVATE KEY-----
  public_key: |
    -----BEGIN PUBLIC KEY-----
    MCowBQYDK2VwAyEAA7JbAsB32+qlwJK4mKRxUVyCivbLp9M0GI9zaP35Jes=
    -----END PUBLIC KEY-----