### signup user

POST http://localhost:8888/api/signup
Content-Type: application/json

{
"workspace": "acme", "fullname": "Alice", "email": "alice@acme.org", "password": "123456"
}

### signup user

POST http://localhost:8888/api/signup
Content-Type: application/json

{
"workspace": "acme", "fullname": "Alice Chen", "email": "alice@acme.org", "password": "123456"
}

### signup user

POST http://localhost:8888/api/signup
Content-Type: application/json

{
"workspace": "acme", "fullname": "Bob Hua", "email": "bob@acme.org", "password": "123456"
}

### signin user (invalid)

POST http://localhost:8888/api/signin
Content-Type: application/json

{
"email": "alice@acme.org", "password": "a123456"
}

### signin user (valid)

# @name signin
POST http://localhost:8888/api/signin
Content-Type: application/json

{
"email": "alice@acme.org", "password": "123456"
}
@token = {{signin.response.body.token}}


### Download file
GET http://localhost:8888/api/download/1/857/5d6/a1a688d0ea3d92d950c178de788f121b87.png
Authorization: Bearer {{token}}
